ibexa.compatibility_layer.oss:
    resource: '@IbexaCompatibilityLayerBundle/Resources/config/deprecated_routing_oss.yaml'

ibexa.compatibility_layer.content:
    resource: '@IbexaCompatibilityLayerBundle/Resources/config/deprecated_routing_content.yaml'

ibexa.compatibility_layer.experience:
    resource: '@IbexaCompatibilityLayerBundle/Resources/config/deprecated_routing_experience.yaml'

ibexa.compatibility_layer.commerce:
    resource: '@IbexaCompatibilityLayerBundle/Resources/config/deprecated_routing_commerce.yaml'
